# Generated by Django 2.0.9 on 2019-01-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article_url', models.URLField(null=True)),
                ('release_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('PRtimes_URL', models.URLField()),
                ('official_URL', models.URLField(null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('tel_number', models.CharField(max_length=100, null=True)),
                ('CEO', models.CharField(max_length=100, null=True)),
                ('jojo', models.CharField(max_length=100, null=True)),
                ('fund', models.CharField(max_length=100, null=True)),
                ('is_client', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('app', models.CharField(max_length=30)),
                ('entertainment', models.CharField(max_length=30)),
                ('beauty', models.CharField(max_length=30)),
                ('fashion', models.CharField(max_length=30)),
                ('lifestyle', models.CharField(max_length=30)),
                ('business', models.CharField(max_length=30)),
                ('gourmet', models.CharField(max_length=30)),
                ('sports', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlApp.CompanyInfo'),
        ),
        migrations.AddField(
            model_name='article',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawlApp.CompanyInfo'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='crawlApp.Tag', verbose_name='ジャンルタグ'),
        ),
    ]
