# Generated by Django 2.0.9 on 2018-12-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.URLField(null=True),
        ),
    ]
