# Generated by Django 2.0.9 on 2018-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
    ]
