# Generated by Django 2.0.9 on 2018-12-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlApp', '0002_article_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='CEO',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='fund',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='jojo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='official_URL',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tel_number',
            field=models.IntegerField(null=True),
        ),
    ]
